language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - npm install
before_script:
  - npm install -g gulp
script:
  - build.sh
  - gulp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t 1025518502/shoping-shop:latest .
  - docker push 1025518502/shoping-shop:latest